#!/usr/bin/bash

# author: Vaisakh Murali <mvaisakh@statixos.com>

#
# Before you start, make sure you squash all split OEM commits into
# one single commit. This will break down the single huge commit
# into multiple smaller commits, helping to cleanup OEM codes easier.
#
# Make sure this script is renamed to rebase.sh as the script
# explicitly removes rebase.sh from being committed during the split
# process.

# Split OEM Changes
echo "Split OEM modifications"

echo "Initial reset"
git reset HEAD^ . >/dev/null 2>&1
echo "Committing a starting point commit (This commit might be authored by the original OEM author)"
git commit -sm "BEGIN OEM Imports" --allow-empty --amend >/dev/null 2>&1

echo "Splitting commits... (This might take a while, do not interrupt)"
DIFFPATHS=(
"arch/arm64/boot"
"arch/arm64/configs"
"arch/arm64/include"
"arch/arm64/kernel"
"arch/arm64/mm"
"arch/arm64/net"
"arch/um"
"arch/um/include/asm"
"arch/um/kernel"
"arch"
"block"
"drivers/adsp_factory"
"drivers/android"
"drivers/base"
"drivers/battery"
"drivers/block"
"drivers/block/zram"
"drivers/char"
"drivers/clk"
"drivers/clk/qcom"
"drivers/connector"
"drivers/cpufreq"
"drivers/cpuidle/governors"
"drivers/dma-buf"
"drivers/dma-buf/heaps"
"drivers/edac"
"drivers/fingerprint"
"drivers/firmware"
"drivers/firmware/cirrus"
"drivers/gpu/drm"
"drivers/hid/usbhid"
"drivers/hwmon/sec_thermistor"
"drivers/hwtracing/coresight"
"drivers/i2c/busses"
"drivers/input/air"
"drivers/input/input_boost"
"drivers/input/misc"
"drivers/input/misc/hall"
"drivers/input/sec_input"
"drivers/interconnect/qcom"
"drivers/iommu"
"drivers/iommu/arm/arm-smmu"
"drivers/kperfmon"
"drivers/leds"
"drivers/md"
"drivers/media/platform/msm/synx"
"drivers/mfd"
"drivers/mfd/maxim"
"drivers/mfd/slsi"
"drivers/misc"
"drivers/misc/drb"
"drivers/misc/tzdev"
"drivers/mmc"
"drivers/mmc/core"
"drivers/mmc/host"
"drivers/muic"
"drivers/net/dropdump"
"drivers/net/ethernet/broadcom"
"drivers/nfc"
"drivers/nfc/nfc_logger"
"drivers/nfc/snvm"
"drivers/of"
"drivers/optics"
"drivers/pci"
"drivers/pci/controller"
"drivers/phy"
"drivers/pinctrl/qcom"
"drivers/power/reset"
"drivers/regulator"
"drivers/regulator/pmic_class"
"drivers/regulator/s2dos05"
"drivers/regulator/s2mpb02"
"drivers/remoteproc"
"drivers/rpmsg"
"drivers/rtc"
"drivers/samsung"
"drivers/scsi/ufs"
"drivers/sec_panel_notifier"
"drivers/secdp"
"drivers/sensors"
"drivers/sensors_lego"
"drivers/slimbus"
"drivers/soc/qcom"
"drivers/soc/qcom/dcvs"
"drivers/soc/qcom/qdsp6v2"
"drivers/spi"
"drivers/staging/greybus/tools"
"drivers/sti"
"drivers/switch"
"drivers/thermal"
"drivers/thermal/qcom"
"drivers/tty"
"drivers/tty/serial"
"drivers/uh"
"drivers/usb"
"drivers/usb/common/vbus_notifier"
"drivers/usb/core"
"drivers/usb/dwc3"
"drivers/usb/gadget"
"drivers/usb/gadget/function"
"drivers/usb/host"
"drivers/usb/misc"
"drivers/usb/notify"
"drivers/usb/phy"
"drivers/usb/repeater"
"drivers/usb/storage"
"drivers/usb/typec/common"
"drivers/usb/typec/manager"
"drivers/usb/typec/maxim"
"drivers/uwb"
"drivers/vibrator"
"drivers/virt/gunyah"
"drivers/watchdog"
"drivers"
"firmware"
"fs/erofs"
"fs/f2fs"
"fs/overlayfs"
"fs/proc"
"fs"
"include/asm-generic"
"include/dt-bindings"
"include/dt-bindings/battery"
"include/dt-bindings/samsung"
"include/kunit"
"include/linux"
"include/linux/adsp"
"include/linux/battery"
"include/linux/firmware/cirrus"
"include/linux/hall"
"include/linux/input"
"include/linux/mfd"
"include/linux/mfd/firmware"
"include/linux/mfd/samsung"
"include/linux/muic"
"include/linux/platform_data"
"include/linux/regulator"
"include/linux/samsung"
"include/linux/sensor"
"include/linux/soc/qcom"
"include/linux/sti"
"include/linux/usb"
"include/linux/usb/typec"
"include/linux/vibrator"
"include/net"
"include/soc/qcom"
"include/sound"
"include/sound/cirrus"
"include/sound/samsung"
"include/trace/events"
"include/trace/hooks"
"include/uapi/asm-generic"
"include/uapi/linux"
"include/uapi/linux/android"
"init"
"kernel/bpf"
"kernel/dma"
"kernel/irq"
"kernel/locking"
"kernel/power"
"kernel/printk"
"kernel/rcu"
"kernel/sched"
"kernel/sched/walt"
"kernel/time"
"kernel/trace"
"kunitconfigs"
"kernel"
"lib/kunit"
"lib"
"mm"
"net/core"
"net/ipv4"
"net/ipv4/netfilter"
"net/ipv6"
"net/ipv6/netfilter"
"net/mac80211"
"net/netfilter"
"net/qrtr"
"net/wireless"
"net/xfrm"
"scripts/lego"
"scripts/mod"
"scripts"
"security/selinux"
"security/selinux/include"
"security/selinux/ss"
"security"
"sound/core"
"sound/soc"
"sound/soc/codecs"
"sound/soc/samsung"
"sound/usb"
"tools"
)

for ELEMENT in ${DIFFPATHS[@]}; do
	[[ -d $ELEMENT ]] && git add $ELEMENT -f >/dev/null 2>&1
	git commit -m "$ELEMENT: Import SAMSUNG changes" >/dev/null 2>&1
done

echo "Done with subdirectories, now committing rest of the changes"

REMNANTDIRS=(
    "arch"
    "bindings"
    "block"
    "certs"
    "crypto"
    "Documentation"
    "drivers"
    "firmware"
    "fs"
    "include"
    "init"
    "io_uring"
    "ipc"
    "kernel"
    "kunitconfigs"
    "lib"
    "LICENSES"
    "mm"
    "net"
    "samples"
    "scripts"
    "security"
    "sound"
    "tools"
    "usr"
    "virt"
    ".gitattributes"
    ".legofile"
    "Makefile"
    "build.config.common"
    "build.config.msm.common"
    "build.config.msm.kalama"
    "build.config.msm.kalama.sec"
    "build.config.sec"
    "build.targets"
    "extmod.mk"
    "lego.config"
    "modules.list.msm.kalama"
    "modules.vendor_blocklist.kunit"
)

for ELEMENT in ${REMNANTDIRS[@]}; do
	[[ -d $ELEMENT ]] && git add $ELEMENT -f >/dev/null 2>&1
	git commit -m "$ELEMENT: Import rest of the SAMSUNG changes" >/dev/null 2>&1
done

git add -- . :!rebase.sh :!out >/dev/null 2>&1
git commit -sm "kernel: Import rest of misc SAMSUNG changes" >/dev/null 2>&1

echo "Committing End point"
git commit -sm "END OEM IMPORTS" --allow-empty >/dev/null 2>&1

echo "Done with imports!"
